FROM bitnami/nginx:latest
USER root
COPY config/nginx.conf /opt/bitnami/nginx/conf/server_blocks/wger.conf
RUN rm -rf /opt/bitnami/nginx/conf/server_blocks/default.conf \
    /opt/bitnami/nginx-agent \
    /opt/bitnami/common/bin/render-template \
    /opt/bitnami/common/.spdx-render-template.spdx
USER 1001
